from Bio.Seq import Seq

def test_rna_prot():
   rna = Seq("AUGGCCAUUGUAAUGGGCCGCUGAAAGGGUGCCCGAUAG")
   assert Seq("MAIVMGR*KGAR*") == rna.translate()

def test_rna_prot_example2():
   dna = Seq("ATGGCCATTGTAATGGGCCGCTGAAAGGGTGCCCGATAG")
   rna = Seq("AUGGCCAUUGUAAUGGGCCGCUGAAAGGGUGCCCGAUAG")

   assert Seq("MAIVMGR*KGAR*") == dna.translate()
   assert Seq("MAIVMGR*KGAR*") == rna.translate()

def test_rna_stop():
   rna = Seq("AUGGCCAUUGUAAUGGGCCGCUGAAAGGGUGCCCGAUAG")
   assert Seq("MAIVMGR") == rna.translate(to_stop=True)


def test_rna_gene():
   gene = Seq(
       "GTGAAAAAGATGCAATCTATCGTACTCGCACTTTCCCTGGTTCTGGTCGCTCCCATGGCA"
       "GCACAGGCTGCGGAAATTACGTTAGTCCCGTCAGTAAAATTACAGATAGGCGATCGTGAT"
       "AATCGTGGCTATTACTGGGATGGAGGTCACTGGCGCGACCACGGCTGGTGGAAACAACAT"
       "TATGAATGGCGAGGCAATCGCTGGCACCTACACGGACCGCCGCCACCGCCGCGCCACCAT"
       "AAGAAAGCTCCTCATGATCATCACGGCGGTCATGGTCCAGGCAAACATCACCGCTAA"
   )

   assert (
       Seq(
           "VKKMQSIVLALSLVLVAPMAAQAAEITLVPSVKLQIGDRDNRGYYWDGGHWRDHGWWKQH"
           "YEWRGNRWHLHGPPPPPRHHKKAPHDHHGGHGPGKHHR*"
       ) == gene.translate(table="Bacterial")
   )